export const shopDepartmentTitles = [
  'Каталог',
  'Здоровье',
  'Красота',
  'Развлечения',
  'Авто',
];

export const discountCardsInfo = [
  {
    title: 'пробка на мира',
    message: 'Вечер для двоих',
    amount: '50%',
    description: 'скидка',
    image: 'wine',
  },
  {
    title: 'кино и немцы',
    message: 'Бесплатный бокал пива',
    amount: 'ВАРВАР',
    description: 'промокод',
    image: 'wine',
  },
  {
    title: 'valery cakes',
    message: 'Торт',
    amount: '30%',
    description: 'скидка',
    image: 'wine',
  },
  {
    title: 'пробка на мира',
    message: 'Вечер для двоих',
    amount: '50%',
    description: 'скидка',
    image: 'wine',
  },
  {
    title: 'кино и немцы',
    message: 'Бесплатный бокал пива',
    amount: 'ВАРВАР',
    description: 'промокод',
    image: 'wine',
  },
  {
    title: 'valery cakes',
    message: 'Торт',
    amount: '30%',
    description: 'скидка',
    image: 'wine',
  },
  {
    title: 'пробка на мира',
    message: 'Вечер для двоих',
    amount: '50%',
    description: 'скидка',
    image: 'wine',
  },
  {
    title: 'кино и немцы',
    message: 'Бесплатный бокал пива',
    amount: 'ВАРВАР',
    description: 'промокод',
    image: 'wine',
  },
  {
    title: 'valery cakes',
    message: 'Торт',
    amount: '30%',
    description: 'скидка',
    image: 'wine',
  },
  {
    title: 'пробка на мира',
    message: 'Вечер для двоих',
    amount: '50%',
    description: 'скидка',
    image: 'wine',
  },
  {
    title: 'кино и немцы',
    message: 'Бесплатный бокал пива',
    amount: 'ВАРВАР',
    description: 'промокод',
    image: 'wine',
  },
  {
    title: 'valery cakes',
    message: 'Торт',
    amount: '30%',
    description: 'скидка',
    image: 'wine',
  },
];
